baseurl = "https://samuelkarp.com/"
languageCode = "en-US"
title = "Samuel Karp - samuelkarp.com"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-40180608-1"
theme = "sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "sam.jpg"
  author = "Samuel Karp"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "samuelkarp"
  Twitter       = "samuelkarp"
  LinkedIn      = "samuelkarp"
  Stackoverflow = "users/112821/samuel-karp"

[params.bio]
  Title    = "Senior Software Development Engineer"
  Location = "Seattle, WA"
[params.bio.company]
  Name    = "Amazon Web Services, Inc."
  Website = "https://aws.amazon.com"

[params.bio.product]
  Name    = "Amazon Elastic Container Service"
  Website = "https://ecs.aws"

## Main Menu
[[menu.main]]
  name = "about"
  weight = 100
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "talks"
  identifier = "talks"
  weight = 200
  url = "/talks/"
[[menu.main]]
  name = "blog"
  identifier = "blog"
  weight = 300
  url = "https://blog.samuelkarp.com"
